version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file: .env
    environment: # define environment variables inside the container
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data   # map datas created in postgres containers to the current folder
    ports:
      - 5432:5432 # postgres default server port is 5432, the port is already exposed when its image was created


  adminer:   # database adminer
    depends_on: 
      - db # start the db container first then this GUI
    image: adminer
    restart: always
    ports:
      - 8080:8080


# create a (local) volume in the host machine first
# you can find a local volume location by docker inspect 'volume name'
# I'mma disable window in several months
volumes:  
  postgres-data:
    external: true